package handler

import (
	"net/http"
	"os"
)

const scalarHTML = `<!doctype html>
<html lang="en">
  <head>
    <title>Myroku API Docs</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <script id="api-reference" data-url="/swagger.json"></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>`

type DocsHandler struct {
	openAPIPath string
}

func NewDocs(openAPIPath string) *DocsHandler {
	return &DocsHandler{openAPIPath: openAPIPath}
}

// UI serves the Scalar API reference page.
// The page itself is intentionally undocumented in the spec.
func (h *DocsHandler) UI(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write([]byte(scalarHTML))
}

// Spec serves the swagger.json file generated by `swag init`.
func (h *DocsHandler) Spec(w http.ResponseWriter, r *http.Request) {
	data, err := os.ReadFile(h.openAPIPath)
	if err != nil {
		http.Error(w, `{"error":"spec not generated yet — run 'make swag'"}`, http.StatusServiceUnavailable)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(data)
}
